/*

 CHURCH_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\dell\Documents\2 Proyectos personales\2 Programación\GB_Tile_designer\Archivos_editables\Church_tiles\church_tiles_set.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define church_mapWidth 20
#define church_mapHeight 18
#define church_mapBank 0

extern unsigned char church_map[];

/* End of CHURCH_MAP.H */
