/*

 INTERIOR_CHURCH_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 40 x 18
   Tile set      : C:\Users\dell\Documents\2 Proyectos personales\2 Programación\GB_Tile_designer\Archivos_editables\Church_tiles\interior_church_tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define interior_mapWidth 40
#define interior_mapHeight 18
#define interior_mapBank 0

extern unsigned char interior_map[];

/* End of INTERIOR_CHURCH_MAP.H */
