/*

 DIALOGUE1_W.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 3
   Tile set      : C:\Users\dell\Documents\2 Proyectos personales\2 Programaci�n\GB_Tile_designer\Archivos_editables\01\rouse_portrait.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define r_dialogue_001Width 20
#define r_dialogue_001Height 3
#define r_dialogue_003Bank 0

extern unsigned char r_dialogue_003[];

/* End of DIALOGUE1_W.H */
